name: pydata-book
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - beautifulsoup4=4.6.0
  - jupyter=1.0.0
  - lxml=4.1.0
  - matplotlib=2.1.0
  - numpy=1.13.3
  - pandas=0.21.0
  - patsy=0.4.1
  - python=3.6.11
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - seaborn=0.8.1
  - statsmodels=0.8.0